CREATE TABLE Users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  description TEXT,
  isPublic BOOLEAN DEFAULT false,
  userId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT,
  templateId INT,
  position INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  content TEXT,
  userId INT,
  templateId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Likes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT,
  templateId INT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
